SELECT patientunitstayid, intakeoutputoffset, cellpath, celllabel, CAST(cellvaluenumeric AS float4) as cellvalue
FROM intakeoutput
WHERE TRIM(cellpath) in -- whitespace is removed from cellpath values
    (
      -- dialysis
      'flowsheet|Flowsheet Cell Labels|I&O|Dialysis (ml)|In',
      'flowsheet|Flowsheet Cell Labels|I&O|Dialysis (ml)|Out',
      
      -- insulin
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Insulin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|INSULIN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|insulin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Insulin Drip (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|INSULIN GTT',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|INsulin IV',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|insulin regular',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|insulin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Insulin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|INSULIN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Insulin drip',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Insulin Drip',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|INSULIN DRIP',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Insulin Gtt',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (ml) Insulin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL) Insulin', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN with insulin',

      -- TPN
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|tpn',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Intake, TPN/PPN Amount',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|TPN Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL) TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|Enteral TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|PPN/TNA/TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN w/fat emulsion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN w/fat emulsion 20%',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN with H2 Blocker',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN/PPN Intake Amount',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|TPN:',

      -- Colloids + Albumin
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|25% Albumin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|25% Albumin 100 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|25% Albumin 50 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|5% Albumin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|5% Albumin 500 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Colloids (ml)|Colloids Total',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|albumin',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-albumin human (SPA) 25 % injection 12.5 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-albumin human (SPA) 25 % injection 25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-albumin human 5 % injection',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-albumin human 5 % injection 12.5 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-albumin human 5 % injection 25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ALBUMIN HUMAN 5 % IV SOLN Pyxis Override',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Albumin 25%',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Albumin 5%',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 25 % injection 12.5 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 25 % injection 25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 25 % solution 25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 5 % injection 12.5-25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 5 % injection 12.5 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 5 % injection 25 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 5 % solution 12.5 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-albumin human 5 % solution 250 mL',

      -- saline solutions exluding those containing dextrose
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/100 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/20 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/75 mEq NaHCO3',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS  w/75 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|1.5% NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|1/2 NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Amiodarone (0.45% NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Bumetanide (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Diltiazem (0.45% NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Dobutamine (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Epinephrine (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Fentanyl (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Heparin (NS 0.45%)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Labetalol (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Midazolam (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Nicardipine (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/ mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/15 mmol (as PO4) KPO4 250 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/15 mmol (as PO4) NaPO4 250 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/150 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/20 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/30 mmol (as PO4) KPO4',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/30 mmol (as PO4) KPO4 250 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/30 mmol (as PO4) KPO4 500 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/40 mEq KCL 500 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/45 mmol (as PO4) KPO4 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/45 mmol (as PO4) KPO4 500 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS  w/60 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS @ KVO',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS + Abx',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS + ABX',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS + ADD',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS 1.5%',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS Addits', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS Bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS BOLUS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS flushes',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS KVO',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS TKO',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS w/ abx',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS with 20KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS/abx',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS+abx',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS+KCl',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NSS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NSS w/ abx',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Octreotide (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Pantoprazole (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Phenylephrine (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Vasopressin (NS)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-Dextran 40 in sodium chloride (DEXTRAN 40 IN NS) 10-0.9 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|0.9 NS_c',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|0.9NS with 20mEq KCL_c',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|1/2 NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|1/2NS + ADD',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|1/2NS + KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|1/2NS IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS + ADD',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS + KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS 0.9% Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS b IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS c IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS d IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS e IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS for Blood Administration',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS w/KCl 20mEq Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ondansetron (ZOFRAN) 8 mg/NS 50 ml IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-0.45 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-0.9 %  sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-Ampicillin-Sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin (OMNIPEN) 12 g in sodium chloride 0.9 % 500 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ampicillin (OMNIPEN) 2 g in sodium chloride 0.9 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-calcium gluconate 1 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefepime (MAXIPIME) 1 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefepime (MAXIPIME) 2 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-erythromycin (ERYTHROCIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-folic acid (FOLVITE) 1 mg in sodium chloride 0.9 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-imipenem-cilastatin (PRIMAXIN) 250 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-imipenem-cilastatin (PRIMAXIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-levETIRAcetam (KEPPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-levETIRAcetam (KEPPRA) 1,500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-levETIRAcetam (KEPPRA) 250 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-levETIRAcetam (KEPPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-levETIRAcetam (KEPPRA) 750 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-meropenem (MERREM) 2 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-micafungin 100 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-Micafungin Sodium 100 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 2.25 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL EXTENDED INFUSION IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL FOUR HOUR EXTENDED INFUSION IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL thirty minute IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL thirty minute IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride (hypertonic) 3 % solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.225 % with sodium bicarbonate 100 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.45 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.45 % 1,000 mL with potassium chloride 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 100 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 10 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL with thiamine 100 mg, folic acid 1 mg, multivitamins adult 10 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % bolus 1,000 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % bolus 250 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % bolus 500 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 10 mmol in sodium chloride 0.9 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium glycerophosphate (GLYCOPHOS) 20 mmol in sodium chloride 0.9 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-tigecycline (TYGACIL) 50 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-tranexamic acid 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-valproate (DEPACON) 500 mg in sodium chloride 0.9 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in sodium chloride 0.9 % 500 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in sodium chloride 0.9 % 500 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 2,000 mg in sodium chloride 0.9 % 500 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 150 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (ml) Heparin-heparin infusion 2 units/mL in 0.9% sodium chloride (ARTERIAL LINE)',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume Infused (ml)-fentaNYL 20 mcg/mL in sodium chloride 0.9% 30 mL PCA infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume Infused (ml)-HYDROmorphone (DILAUDID) 0.4 mg/mL in sodium chloride 0.9% 30 mL PCA infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume Infused (ml)-morphine (ASTRAMORPH PF) 100 mcg/mL, bupivacaine PF (SENSORCAINE-MPF) 0.125 % in sodium chloride 0.9 % 100 mL epidural infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume Infused (ml)-morphine 2 mg/mL in sodium chloride 0.9% 30 mL PCA infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|1.5% saline',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|3% saline',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Hypertonic saline 3%', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Saline Flush (mL)',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 1,000 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 250 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride (NORMAL SALINE) 0.9 % bolus 500 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers 1,000 mL with thiamine 100 mg, folic acid 1 mg, magnesium sulfate 2 g infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers bolus 1,000 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers bolus 500 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers infusion 1,000 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Lactated Ringers Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-lactated ringers 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-lactated ringers infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-lactated ringers infusion 500 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR  w/60 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR Bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|LR',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|LR IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|1.5% NaCl',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NaCl 1.5%',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.45 % sodium chloride solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.45 % sodium chloride with KCl 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.9 % sodium chloride solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.9 % sodium chloride with potassium chloride 20 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.9% sodium chloride with potassium chloride 40 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ampicillin-sulbactam (UNASYN) 1.5 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ampicillin-sulbactam (UNASYN) 3 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ampicillin (OMNIPEN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-azithromycin (ZITHROMAX) 500 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-aztreonam (AZACTAM) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-aztreonam (AZACTAM) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-Calcium gluconate 10 g in 0.9% sodium chloride 250 ml infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ceFAZolin (ANCEF) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ceFAZolin 2,000 mg in sodium chloride 0.9% 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ceFEPIme (MAXIPIME) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ceFEPIme (MAXIPIME) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-clindamycin 600 mg in sodium chloride 0.9% 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-clindamycin 900 mg in sodium chloride 0.9% 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-hydrocortisone sod succ PF (Solu-CORTEF) 250 mg in sodium chloride 0.9 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-levETIRAcetam (KepPRA) 1,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-levETIRAcetam (KepPRA) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-magnesium sulfate 2 g in sodium chloride 0.9% IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-meropenem (MERREM) 1 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-meropenem (MERREM) 500 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-micafungin (MYCAMINE) 100 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-nafcillin (NAFCIL) 2,000 mg in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 3.375 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) 4.5 g in sodium chloride 0.9 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 50 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.45 % 1,000 mL with sodium bicarbonate 75 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.45 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.45 % with KCl 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL IV bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 2,000 mL IV bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 250 mL IV bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 500 mL IV bolus',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % with KCl 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9% infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 3 % solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-calcium chloride 100 mEq in sodium chloride 0.9 % 1,000 mL infusion (CRRT with citrate anticoag)',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,000 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-vancomycin (VANCOCIN) 750 mg in sodium chloride 0.9 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-vancomycin 1,250 mg in sodium chloride 0.9% 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-vancomycin 1,500 mg in sodium chloride 0.9% 250 mL IVPB',
      
      -- total nutrition intake
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Nutrition (ml)|Nutrition Total',

      -- Dextrose solutions 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-anticoagulant citrate/dextrose formula A (ACD FORMULA A) infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-calcium gluconate 2 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-ciprofloxacin (CIPRO) 400 mg in dextrose 5% 200 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextran 40 in dextrose 5% (DEXTRAN 40 IN D5W) 10 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 10 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 15 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 %-0.45 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / lactated ringers infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with magnesium sulfate 5 g infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.45% 1,000 mL with potassium chloride 40 mEq, magnesium sulfate 5 g infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.45% infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.45% with KCl 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.9% with KCl 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 100 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 50 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.2 % sodium chloride 1,000 mL with sodium bicarbonate 100 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.2 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.2% sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 20 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.45 % sodium chloride with KCl 40 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.45% NaCl infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 50 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.45% sodium chloride 1,000 mL with sodium bicarbonate 75 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.9 % sodium chloride with KCl 20 mEq/L',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.9% NaCl infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.9% sodium chloride 1,000 mL with potassium chloride 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % in lactated ringers infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5% with KCL 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 500 mg',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-levofloxacin (LEVAQUIN) in dextrose 5% premix IVPB 750 mg',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-magnesium sulfate 1 g in dextrose 5% 100 mL IVPB premix',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-piperacillin-tazobactam (ZOSYN) in dextrose 5% premix IVPB 3.375 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-potassium phosphate 15 mmol in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5% 1000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium phosphate 15 mmol in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-azithromycin (ZITHROMAX) 500 mg in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-aztreonam (AZACTAM) 1 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-aztreonam (AZACTAM) 2 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ceFEPIme (MAXIPIME) 1 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ceFEPIme (MAXIPIME) 2 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTAZidime (FORTAZ) 1 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTAZidime (FORTAZ) 2 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 1 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefTRIAXone (ROCEPHIN) 2 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-cefUROXime (ZINACEF) 1.5 g in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 10 % infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 %-0.45 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % 1,000 mL with potassium chloride 40 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % 1,000 mL with sodium bicarbonate 150 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.2 % NaCl infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 10 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 20 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 30 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.45 % NaCl with KCl 40 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.45% NaCl 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 20 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9% NaCl 1,000 mL with potassium chloride 20 mEq infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % in lactated ringers infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % solution',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % with KCl 20 mEq / L  infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-doxycycline (VIBRAMYCIN) 100 mg in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-furosemide (LASIX) 120 mg in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-furosemide (LASIX) 160 mg in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-magnesium sulfate in 5 % dextrose IVPB 1 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-magnesium sulfate in dextrose premix 2 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-penicillin G potassium 2.5 Million Units in dextrose 5 % 100 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-potassium phosphate 10 mmol in dextrose 5 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-potassium phosphate 20 mmol in dextrose 5 % 500 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-potassium phosphate 30 mmol in dextrose 5 % 500 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium bicarbonate 100 mEq in dextrose 5 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium bicarbonate 150 mEq in dextrose 5 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium bicarbonate 50 mEq in dextrose 5 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium bicarbonate 75 mEq in dextrose 5 % 1,000 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium phosphate 10 mmol in dextrose 5 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium phosphate 20 mmol in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium phosphate 30 mmol in dextrose 5 % 250 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-valproate (DEPACON) 500 mg in dextrose 5 % 50 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,250 mg in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,500 mg in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 1,750 mg in dextrose 5 % 500 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin (VANCOCIN) 750 mg in dextrose 5 % 250 mL IVPB',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin in dextrose premix 1 g',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-vancomycin in dextrose premix 1,000 mg',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (ml) Heparin-heparin 25,000 units in dextrose 500 mL infusion',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D10',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D10 NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D10NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D10W',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D10W',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.2 NS', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/10 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/20 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/20 mEq KCL and 10 mmol (as PO4) KPO4',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 0.45 NS  w/75 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 1/2NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 LR', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5.45NS+KCl',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS  w/150 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS  w/20 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W', 
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/ mEq NaHCO3',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/100 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/150 mEq NaHCO3',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/150 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/20 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/20 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/40 mEq KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/40 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/50 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/60 mEq KCL 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5W  w/75 mEq NaHCO3 1000 ml',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Heparin (D5W)-IN',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium bicarbonate in D5W premix 150 mEq/1000 mL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 1/2 NS Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 1/2 NS w/KCl 20mEq Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 1/2NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 1/2NS + KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 LR Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5 NS',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D51/2NS IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D51/4NS IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5LR IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5NS + KCL',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5NS IVF',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5NS Volume',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5W',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|D5W + ADD',
      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-ceFAZolin (ANCEF) in d5w 2 g premix',

      -- CRRT (output)
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|CRRT- UF removed',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|CRRT - UF removed',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|CRRT Actual Pt Fluid Removed ("C")',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|CRRT Out',

      -- Foley and Urine
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|incontinent urine',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|OR urine',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-External Urethral Device', 
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-External Urethral Device Condom catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-External Urinary Catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter A. Haggard RN  Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter A. Hegarty, RN Latex;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter A. Hegarty, RN Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Amanda Lee  Latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Amanda Stranten EMT Latex;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Anne Lowe RN 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter April Whitlow EMT Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter B Jacobelli, RN Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Brittany Davis RN Non-latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter C. Wofford Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Chasity Yates, RN Latex;Straight-tip;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Chasity Yates, RN Latex;Temperature probe;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Chasity Yates, RNFA Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Chip Harris, RN  Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Christa McClellen Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Christian Smith RN/ Laura Caudle RN  Latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Christine Hinshaw, RN Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Christy Golden RN 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Cory Vaughn, EMT Latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Coude 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Coude 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Darrell, EMT  Latex;Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Deanna Revis, RN and Rose Cullom, RN Non-latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter DeLisa Cobb, RN   Megan Stocks RN Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Diana Acuna, RN Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Diana Acuna, RN Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Diana Acuna, RN Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Diana Acuna, RN Latex;Straight-tip;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Diane Wilson, RN Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Double-lumen',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Double-lumen 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Double-lumen 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter dr macdermid Non-latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Dr Wrenn',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter emt-liza Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Greg Meadows RN Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter hayley ringley rn Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Hayley Ringley, RN/ Dr. Thompson Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Heather Richard Rn Latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter James Dunlop RN Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter James RN Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter John NT+3, Carrie RN Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Josh McDaniel, RN Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Josh Paramedic 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter k hyatt RN Non-latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter K. Hardy RNFA Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter K. Hardy RNFA Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter K. Lawless, RN Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Kimyona Ray, Jennifer Bishop 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Kristi Lawless, RN Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Kristi Lawless, RN Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter L. Simpson, RN Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter L. Taylor, RN Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex 10 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Straight-tip;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Straight-tip;Temperature probe;Triple-lumen 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Straight-tip;Temperature probe;Triple-lumen 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Temperature probe;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Latex;Temperature probe;Straight-tip;Triple-lumen',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter LF, SN Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter M Troha RN Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter M. Irwin RNFA Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter M. Tice, RN Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Maria Pelance, RN Latex;Straight-tip;Temperature probe;Triple-lumen 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Marie Irwin, RN Latex;Straight-tip;Temperature probe;Triple-lumen 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Marie Irwin, RNFA Latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Mavis , NR Latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Mavis Nyako RN 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Natalie,RN Non-latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex;Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Non-latex;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter P Weatherly RNFA Latex;Straight-tip;Temperature probe;Triple-lumen 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Sara Early, RN Non-latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Sarah Burnham, RN and Jordan Perkins, RN Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter sheilla ridenhour 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Stephanie DeHart, RN Latex;Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Stormie Duffy RN Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Straight-tip',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Straight-tip 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Straight-tip;Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter T Davis Latex;Straight-tip 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter tawanda nt',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Teal Curry, RN  Straight-tip',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe;Latex 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe;Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe;Non-latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe;Non-latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Temperature probe;Straight-tip;Latex',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Victor 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Vina Sananikone, RN Latex 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urethral Catheter Yasemia Lebron, RN Straight-tip 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urinary Catheter  Indwelling',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urinary Catheter Indwelling',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output (mL)-Urinary Catheter Suprapubic catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output Amt-Urinary Catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Output Amt-Urinary Catheter', 
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|SN Urine Output(ml)',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Suprapubic Urine Output',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Condom External',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Condom Urethral',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Coude Urethral',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Coude Urethral 14 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Coude Urethral 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Coude Urethral 18 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Indwelling/Continuous Ext',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Indwelling/Continuous Nep',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Indwelling/Continuous Per',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Indwelling/Continuous Sup',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Indwelling/Continuous Ure',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Nephrostomy L',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Nephrostomy R',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Straight/Intermittent Ure',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Suprapubic',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Urethral',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Catheter Output: Urethral 16 Fr.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Incont.',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|urinary incontinence',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urinary Incontinence',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|URINE CATHETER',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|urine count',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Count',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|urine incontinence',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Incontinence',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Occurrence',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-Nephrostomy',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-RIGHT Nephrouretero Stent Urine Output',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-Urine Output',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output (mL)-Urethral Catheter',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output (mL)-Urethral Catheter', 
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output (mL)-Urethral Catheter ', 
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine, L neph:',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine, void:',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-foley',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-Foley',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Urine Output-FOLEY',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|foley',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Foley',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|FOLEY',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Foley cath',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Foley Cath',
      'flowsheet|Flowsheet Cell Labels|I&O|Output (ml)|Foley catheter'
    );